name: Build and upload Docker image

on:
  push:
    tags:
      - '*'

env:
  REGION: europe-west2
  PROJECT: pacific-tours-424606
  REPO: main
  IMAGE: pacific-tours:ci-cd
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set variables
        run: echo "IMAGE_TAG=$REGION-docker.pkg.dev/$PROJECT/$REPO/$IMAGE" >> $GITHUB_ENV
      

      - name: GC Authorization
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GC_MANAGER_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
  

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: true
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
          category: snyk-sast-analysis


  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Docker Authorization
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}:${{github.ref_name}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  dast:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Run OWASP ZAP scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:5000'
          

      - name: Upload OWASP ZAP report
        uses: actions/upload-artifact@v2
        with:
          name: owasp-zap-report
          path: owasp-zap-report.html

