name: Build and upload Docker image

on:
  push:
    branches:
      - main

env:
  REGION: europe-west2
  PROJECT: pacific-tours-424606
  REPO: main
  IMAGE: pacific-tours:ci-cd

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set variables
        run: echo "IMAGE_TAG=$REGION-docker.pkg.dev/$PROJECT/$REPO/$IMAGE" >> $GITHUB_ENV
      
      - name: GC Authorization
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GC_MANAGER_KEY }}"
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Docker Authorization
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}
