name: pacific-tours build
on:
  push:
    branches: [main]

jobs:
  build-push:
    name: builds and pushes
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: pacific-tours
      PROJECT_ID: exemplary-datum-424606-i6
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_ }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:ci-cd .

    - name: Configure Docker Client
      run: |
        gcloud auth configure-docker --quiet
        
    - name: Push Docker Image to Container Registry
      env:
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:ci-cd gcr.io/$PROJECT_ID/$IMAGE_NAME:ci-cd
        docker tag $IMAGE_NAME:ci-cd gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:ci-cd
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG